################################################################################
# Joshua C. Fjelstul, Ph.D.
# englishfootball R package
# automatically generated by the codebookr R package
################################################################################

#' Appearances
#' 
#' This dataset records all appearances. There is one observation per team per
#' match per season. It indicates whether the team is the home team or the
#' away team, the number of goals for and against, the goal difference,
#' whether the team wins, loses, or draws, and how many points the team earned
#' from the match.
#' 
#' @format A data frame with 22 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{season_id}{\code{text}. The unique ID number for the season.
#' References \code{season_id} in the \code{seasons} dataset.}
#' \item{season}{\code{integer}. The year that the season started.}
#' \item{tier}{\code{integer}. The tier in English football. The possible
#' values are \code{1} through \code{4}.}
#' \item{division}{\code{test}. The division in English football. For the
#' current league structure, the possible values are \code{Premier League},
#' \code{Championship}, \code{League One}, and \code{League Two}. For previous
#' league structures, the possible values are \code{First Division},
#' \code{Second Division}, \code{Third Division}, and \code{Fourth Division}.}
#' \item{subdivision}{\code{test}. The subdivision in English football. In the
#' third tier, from the 1921-22 season through the 1957-58 season, there were
#' North and South subdivisions. The possible values are \code{North},
#' \code{South}, and \code{None}.}
#' \item{match_id}{\code{text}. The unique ID number for the match. References
#' \code{match_id} in the \code{matches} dataset.}
#' \item{match_name}{\code{text}. The name of the match.}
#' \item{team_id}{\code{text}. The unique ID number for the team. References
#' \code{team_id} in the \code{teams} dataset.}
#' \item{team_name}{\code{text}. The name of the team.}
#' \item{opponent_id}{\code{text}. The unique ID number for the team's
#' opponent. References \code{team_id} in the \code{teams} dataset.}
#' \item{opponent_name}{\code{text}. The name of the team's opponent.}
#' \item{home_team}{\code{boolean}. Whether the team was the home team. Coded
#' \code{1} if the team was the home team and \code{0} otherwise.}
#' \item{away_team}{\code{boolean}. Whether the team was the away team. Coded
#' \code{1} if the team was the away team and \code{0} otherwise.}
#' \item{goals_for}{\code{integer}. The number of goals scored by the team.}
#' \item{goals_against}{\code{integer}. The number of goals scored against the
#' team.}
#' \item{goal_difference}{\code{integer}. The team's goal difference.}
#' \item{result}{\code{enum}. The result of the match. The possible values are
#' \code{home team win}, \code{away team win}, and \code{draw}.}
#' \item{win}{\code{boolean}. Whether the team won the match. Coded \code{1}
#' if the team won the match and \code{0} otherwise.}
#' \item{lose}{\code{boolean}. Whether the team lost the match. Coded \code{1}
#' if the team lost the match and \code{0} otherwise.}
#' \item{draw}{\code{boolean}. Whether the match ended in a draw. Coded
#' \code{1} of the match ended in a draw and \code{0} otherwise.}
#' \item{points}{\code{integer}. The number of points the team earned from the
#' match. A team earns \code{0} points for a loss and \code{1} point for a
#' draw. From the 1888-89 season through the 1980-81 season, teams earned
#' \code{2} points for a win. Starting with the 1981-82 season, teams have
#' earned \code{3} points for a win.}
#' }
"appearances"

################################################################################
# end R script
################################################################################

