################################################################################
# Joshua C. Fjelstul, Ph.D.
# englishfootball R package
# automatically generated by the codebookr R package
################################################################################

#' Teams
#' 
#' This dataset records all teams who have competed in the English Football
#' League and the Premier League. There is one observation per team. It
#' indicates the current name of the team, any former names of the team,
#' whether the team is a former member of the Football League, whether the
#' team is defunct, and the season that the team made their first appearance
#' in the Football League.
#' 
#' @format A data frame with 8 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{team_id}{\code{text}. The unique ID number for the team. Has the
#' format \code{T-###}, where the number is a counter that is assigned with
#' the data sorted by the year of the team's first appearance in the Football
#' League and then by the team's name.}
#' \item{team_name}{\code{text}. The current name of the team.}
#' \item{former_team_names}{\code{text}. The former names of the team,
#' separated by a comma. Coded \code{None} for teams that have not changed
#' their name.}
#' \item{current}{\code{boolean}. Whether the team currently competes in the
#' English Football League or the Premier League. Coded \code{1} if the team
#' currently competes in these leagues and \code{0} otherwise.}
#' \item{former}{\code{boolean}. Whether the team no longer competes in the
#' English Football League or the Premier League (but still exists). Coded
#' \code{1} if the team is no longer in these leagues and \code{0} otherwise.}
#' \item{defunct}{\code{boolean}. Whether the team is defunct and no longer
#' exists. Coded \code{1} if the team is defunct and \code{0} otherwise.}
#' \item{first_appearance}{\code{integer}. The season that the team first
#' competed in the Football League.}
#' }
"teams"

################################################################################
# end R script
################################################################################

